Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2020-12, with the labels that each got.

#237 Adding screenshot of InnerSource Portal from SAPs open source project
  patterns/2-structured/innersource-portal.md
Labels: Type - Content Work

#236 Add link to reference implementation (project portal open source project)
  patterns/2-structured/innersource-portal.md
Labels: Type - Content Work

#243 Board Report 2020-12
  meta/boardreports/2020-12.md
  patterns/2-structured/start-as-experiment.md
Labels: Type - Meta

#213 Adding known instance for the 'InnerSource Portal' pattern
  patterns/2-structured/innersource-portal.md
Labels: Type - Content Work

#242 Publish level 2+3 patterns as a gitbook automatically
  .gitbook.yaml
  .github/workflows/book.yml
  book/.gitignore
  book/Gemfile
  book/README.md
  book/contribute-to-this-book.md
  book/generate_toc.rb
  book/innersource-patterns-book-cover.jpg
  book/innersource-program-mind-map.png
  book/introduction.md
  book/toc.md
  book/toc_template.md
  patterns/2-structured/innersource-portal.md
Labels: (Self-) Hosting

#120 pattern/innersource-portal-hygiene
  innersource-portal-hygiene.md
Labels: 1-initial, Type - Content Work

#239 Shortening some pattern titles to make for nicer links
  README.md
  patterns/2-structured/maturity-model.md
  patterns/2-structured/project-setup/base-documentation.md
  patterns/2-structured/project-setup/communication-tooling.md
  patterns/2-structured/project-setup/issue-tracker.md
  patterns/2-structured/service-vs-library.md
Labels: (Self-) Hosting, Type - Content Work

#249 Adding step for new TCs to get added to CODEOWNERS
  TRUSTED-COMMITTERS.md
Labels: Type - Meta

#256 Add author to issue-tracker.md
  patterns/2-structured/project-setup/base-documentation.md
  patterns/2-structured/project-setup/communication-tooling.md
  patterns/2-structured/project-setup/issue-tracker.md
Labels: Type - Content Work

#262 Correctly generate Toc for book if Patlet contains code block
  book/generate_toc.rb
Labels: (Self-) Hosting

#222 chore: Add Markdownlint to CI
  .github/workflows/markdownlint-problem-matcher.json
  .github/workflows/markdownlint.yml
  .markdownlint.json
Labels: (Self-) Hosting

#263 fix: MD010/no-hard-tabs
  .markdownlint.json
  meta/boardreports/2020-11.md
  meta/boardreports/2020-12.md
  meta/contributor-handbook.md
  patterns/2-structured/innersource-portal.md
  patterns/2-structured/maturity-model.md
Labels: Type - Maintenance / Cleanup
