Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2020-04, with the labels that each got.

#145 Add link checker only for README.md
  .github/workflows/main.yml
Labels: Type - Maintenance / Cleanup

#141 Update Process for Instating Trusted Committers
  README.md
  TRUSTED-COMMITTERS.md
  meta/trusted-committers.md
Labels: Type - Meta

#139 Adding Mission Statement + Reworking the intro
  README.md
Labels: Type - Meta

#122 Add first pattern on base documentation.
  project-setup/base-documentation.md
  project-setup/templates/CONTRIBUTING-template.md
  project-setup/templates/README-template.md
Labels: 3 - Do 2nd Review

#153 Move meta info from main README to /meta
  README.md
  meta/README.md
  meta/pattern-system.md
Labels: Type - Maintenance / Cleanup
