Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2020-05, with the labels that each got.

#147 Pattern: InnerSource License
  README.md
  innersource-license.md
Labels: Type - Content Work

#161 Fixes link to pattern discover-your-innersource.md
  README.md
  discover-your-innersource.md
Labels: Type - Maintenance / Cleanup

#164 Remove links from patterns to wiki pages that don't exist any more
  bad-weather-for-liftoff.md
  change-the-developers-mindset.md
  defeat-hierarchical-constraints.md
  developer-incentive-alignment-for-innersource-contribution.md
  organizational-mindset-change.md
  overcome-acquisition-based-silos-developer.md
  overcome-acquisition-based-silos-manager.md
  share-your-code-to-get-more-done.md
  shared-code-repo-different-from-build-repo.md
Labels: Type - Maintenance / Cleanup

#177 Change headlines in README
  README.md
Labels: Type - Maintenance / Cleanup

#123 Add howto documentation on issue tracker usage.
  project-setup/issue-tracker.md
Labels: 3 - Do 2nd Review, B - Unproven (Idea), Type - Content Work
