Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2020-09, with the labels that each got.

#124 Add first draft for communication tooling setup.
  README.md
  patterns/2-structured/project-setup/communication-tooling.md
Labels: 3 - Do 2nd Review, B - Unproven (Idea), Type - Content Work

#204 Initial: Transparent Cross-Team Decision Making using RFCs
  README.md
  patterns/1-initial/transparent-cross-team-decision-making-using-rfcs.md
Labels: Type - Content Work

#121 This adds the maturity model as proposed in #116
  README.md
  patterns/2-structured/maturity-model.md
Labels: 3 - Do 2nd Review, Type - Content Work

#220 Standardize title section
  meta/pattern-template.md
  patterns/2-structured/contracted-contributor.md
  patterns/2-structured/dedicated-community-leader.md
  patterns/2-structured/review-committee.md
Labels: (Self-) Hosting

#221 Fixing typo in Patlet header
  patterns/2-structured/project-setup/base-documentation.md
Labels: Type - Maintenance / Cleanup

#209 Update gig-marketplace.md
  patterns/2-structured/gig-marketplace.md
Labels: Type - Content Work

#199 New Pattern: reluctance to accept contributions
  README.md
  patterns/1-initial/reluctance-to-accept-contributions.md
Labels: 1-initial, Type - Content Work

#102 Added gig-marketplace and innersource-portal patterns
  gig-marketplace.md
  innersource-portal.md
Labels: 3-validated, Stale, Type - Content Work, Type - Maintenance / Cleanup

#223 Fixing some typos in the MaturityModel pattern
  patterns/2-structured/maturity-model.md
Labels: (Self-) Hosting, Type - Maintenance / Cleanup
