Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2020-08, with the labels that each got.

#188 Move patterns to new folders
  README.md
  patterns/1-initial/bad-weather-for-liftoff.md
  patterns/1-initial/change-the-developers-mindset.md
  patterns/1-initial/defeat-hierarchical-constraints.md
  patterns/1-initial/developer-incentive-alignment-for-innersource-contribution.md
  patterns/1-initial/discover-your-innersource.md
  patterns/1-initial/improve-findability.md
  patterns/1-initial/introducing-metrics-in-innersource.md
  patterns/1-initial/junkyard-styled-innersourcing.md
  patterns/1-initial/modular-code.md
  patterns/1-initial/organizational-mindset-change.md
  patterns/1-initial/share-your-code-to-get-more-done.md
  patterns/1-initial/shared-code-repo-different-from-build-repo.md
  patterns/2-structured/30-day-warranty.md
  patterns/2-structured/common-requirements.md
  patterns/2-structured/contracted-contributor.md
  patterns/2-structured/crossteam-project-valuation.md
  patterns/2-structured/dedicated-community-leader.md
  patterns/2-structured/gig-marketplace.md
  patterns/2-structured/innersource-license.md
  patterns/2-structured/innersource-portal.md
  patterns/2-structured/overcome-acquisition-based-silos-developer.md
  patterns/2-structured/overcome-acquisition-based-silos-manager.md
  patterns/2-structured/praise-participants.md
  patterns/2-structured/project-setup/base-documentation.md
  patterns/2-structured/project-setup/issue-tracker.md
  patterns/2-structured/project-setup/templates/CONTRIBUTING-template.md
  patterns/2-structured/project-setup/templates/README-template.md
  patterns/2-structured/review-committee.md
  patterns/2-structured/service-vs-library.md
  patterns/2-structured/start-as-experiment.md
  patterns/2-structured/trusted-committer.md
Labels: Type - Maintenance / Cleanup

#87 Cross-team Project Valuation
  patterns/2-structured/crossteam-project-valuation.md
Labels: 3 - Do 2nd Review

#189 First draft of the "InnerSource Activity Score" pattern
  README.md
  assets/img/repository_activity_score.png
  patterns/2-structured/repository-activity-score.md
Labels: Type - Content Work

#112 Draft pattern: Who is using my code?
  patterns/1-initial/code-consumers.md
Labels: 3 - Do 2nd Review, B - Unproven (Idea), Stale
