Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2021-02, with the labels that each got.

#253 Pattern idea: duplicated-projects.md
  README.md
  patterns/1-initial/duplicated-projects.md
Labels: Type - Content Work

#284 Removing inaccessible pattern: What Before How or Services Documentation
  README.md
Labels: Type - Maintenance / Cleanup

#281 Adds a pattern draft for making governance levels explicit.
  README.md
  patterns/1-initial/governance-levels.md
Labels: Type - Content Work

#46 pattern/open-source-trumps-innersource
  README.md
  assets/img/landscape-of-effective-and-efficient-software-development.png
  patterns/1-initial/open-source-trumps-innersource.md
Labels: 2-structured, Type - Content Work

#63 pattern/change-developers-mindset
  patterns/1-initial/change-the-developers-mindset.md
Labels: 1-initial, Type - Content Work

#78 Change the Middle-Management Mindset
  README.md
  patterns/1-initial/change-the-middle-management-mindset.md
Labels: 1-initial, Type - Content Work

#286 Introducing Hall-of-Fame for former TCs
  .github/CODEOWNERS
  TRUSTED-COMMITTERS.md
Labels: Type - Meta

#291 Introducing Pattern associated with InnerSource project fitness
  patterns/1-initial/good-first-project.md
Labels: 1-initial, Type - Content Work

#292 Link to 'Good First Project' pattern
  .github/workflows/link-checker.yml
  README.md
  patterns/1-initial/good-first-project.md
Labels: Type - Maintenance / Cleanup

#84 Contained InnerSource
  README.md
  patterns/1-initial/contained-innersource.md
Labels: 1-initial, Type - Content Work

#95 Update modular-code.md
  patterns/1-initial/modular-code.md
Labels: 1-initial, Type - Content Work

#289 Incorporate InnerSource-Guideance-Group as an initial pattern
  README.md
  patterns/1-initial/innersource-guidance-group.md
Labels: 1-initial, Type - Content Work

#274 Some cleanup in the 'meta' folder
  assets/img/patterns-steps-and-maturities.png
  meta/FAQ.md
  meta/README.md
  meta/technical-git-howto.md
Labels: Type - Maintenance / Cleanup, Type - Meta

#294 Add links to Europace blog posts
  patterns/2-structured/project-setup/base-documentation.md
  patterns/2-structured/project-setup/issue-tracker.md
Labels: Type - Content Work

#295 Active voice and typos
  book/introduction.md
  patterns/1-initial/developer-incentive-alignment-for-innersource-contribution.md
  patterns/2-structured/innersource-license.md
Labels: Type - Content Work, Type - Maintenance / Cleanup

#300 Fix display of lists in 30 Day Warranty pattern
  patterns/2-structured/30-day-warranty.md
Labels: Type - Maintenance / Cleanup

#301 Fix contracted contributor book display
  patterns/2-structured/contracted-contributor.md
Labels: (Self-) Hosting, Type - Maintenance / Cleanup

#306 Switch to new book URL
  README.md
  book/README.md
  pattern-categorization/innersource-program-mind-map.html
  pattern-categorization/innersource-program-mind-map.md
Labels: (Self-) Hosting

#307 Shorten pattern URLs in the book
  .github/workflows/book.yml
  book/README.md
  book/toc.md
  book/toc_template.md
Labels: (Self-) Hosting

#304 Fixing TBD placeholder in 30 Day Warranty
  patterns/2-structured/30-day-warranty.md
Labels: Type - Content Work

#305 Simplify the "What are InnerSource Patterns?" section
  README.md
Labels: Type - Maintenance / Cleanup

#308 Book Formatting Review
  assets/img/review-committee-sketch.jpg
  patterns/2-structured/common-requirements.md
  patterns/2-structured/crossteam-project-valuation.md
  patterns/2-structured/gig-marketplace.md
  patterns/2-structured/maturity-model.md
  patterns/2-structured/praise-participants.md
  patterns/2-structured/service-vs-library.md
Labels: (Self-) Hosting, Type - Maintenance / Cleanup
