Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2021-01, with the labels that each got.

#257 Custom linter to check the format of the patterns
  .github/workflows/lint-patterns.yml
  lint/pattern-template.js
  lint/pattern-template.yml
Labels: Type - Meta

#264 fix: Markdownlint rules for whitespace
  .markdownlint.json
  CONTRIBUTING.md
  README.md
  meta/FAQ.md
  meta/boardreports/2020-10-details.md
  meta/boardreports/2020-10.md
  meta/boardreports/2020-11.md
  meta/boardreports/2020-12.md
  meta/contributor-handbook.md
  meta/innersource-spelling.md
  meta/pattern-system.md
  meta/pattern-template.md
  meta/technical-git-howto.md
  pattern-categorization/innersource-program-mind-map.md
  patterns/1-initial/code-consumers.md
  patterns/1-initial/developer-incentive-alignment-for-innersource-contribution.md
  patterns/1-initial/discover-your-innersource.md
  patterns/1-initial/improve-findability.md
  patterns/1-initial/innersource-portal-hygiene.md
  patterns/1-initial/introducing-metrics-in-innersource.md
  patterns/1-initial/junkyard-styled-innersourcing.md
  patterns/1-initial/overcome-acquisition-based-silos-developer.md
  patterns/1-initial/overcome-acquisition-based-silos-manager.md
  patterns/1-initial/overcoming-project-management-time-pressures.md
  patterns/1-initial/reluctance-to-accept-contributions.md
  patterns/1-initial/shared-code-repo-different-from-build-repo.md
  patterns/2-structured/common-requirements.md
  patterns/2-structured/contracted-contributor.md
  patterns/2-structured/crossteam-project-valuation.md
  patterns/2-structured/dedicated-community-leader.md
  patterns/2-structured/gig-marketplace.md
  patterns/2-structured/maturity-model.md
  patterns/2-structured/praise-participants.md
  patterns/2-structured/project-setup/templates/CONTRIBUTING-template.md
  patterns/2-structured/repository-activity-score.md
Labels: (Self-) Hosting, Type - Maintenance / Cleanup

#254 Cleanup overview of patterns in Level 1
  README.md
  patterns/1-initial/change-the-developers-mindset.md
  patterns/1-initial/code-consumers.md
  patterns/1-initial/developer-incentive-alignment-for-innersource-contribution.md
  patterns/1-initial/discover-your-innersource.md
  patterns/1-initial/improve-findability.md
  patterns/1-initial/incentive-mechanisms-for-voluntary-contribution.md
  patterns/1-initial/introducing-metrics-in-innersource.md
  patterns/1-initial/junkyard-styled-innersourcing.md
  patterns/1-initial/modular-code.md
  patterns/1-initial/overcome-acquisition-based-silos-developer.md
  patterns/1-initial/overcome-acquisition-based-silos-manager.md
  patterns/1-initial/share-your-code-to-get-more-done.md
  patterns/1-initial/shared-code-repo-different-from-build-repo.md
Labels: Type - Maintenance / Cleanup

#271 Reduce unneeded Pattern Syntax check executions
  .github/workflows/lint-patterns.yml
Labels: Type - Meta

#270 Link to book from README
  README.md
Labels: Type - Meta

#166 initial checkin of concept-anchor
  README.md
  patterns/1-initial/concept-anchor.md
Labels: Type - Content Work

#245 Expand RFC Pattern
  README.md
  patterns/2-structured/templates/rfc.md
  patterns/2-structured/transparent-cross-team-decision-making-using-rfcs.md
Labels: Type - Content Work

#279 Maturity Model: Adds an explanation of what a forge is
  patterns/2-structured/maturity-model.md
Labels: Type - Content Work

#261 Review crossteam-project-valuation
  README.md
  patterns/2-structured/crossteam-project-valuation.md
Labels: Type - Content Work

#71 Create include-product-owners.md
  README.md
  patterns/1-initial/include-product-owners.md
Labels: Type - Content Work

#74 Create assisted_compliance.md
  README.md
  patterns/1-initial/assisted_compliance.md
Labels: 1-initial, Type - Content Work

#252 Spelling and formatting fixes for the Review Committee pattern
  README.md
  patterns/2-structured/review-committee.md
Labels: Type - Content Work

#251 Spelling and formatting fixes for the Trusted Committer pattern
  README.md
  patterns/2-structured/trusted-committer.md
Labels: Type - Content Work
