Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2021-09, with the labels that each got.

#348 Generate mind map automatically (via GHA)
  .github/workflows/generate-mindmap.yml
  book/README.md
  book/explore-patterns.md
  book/innersource-program-mind-map.png
  book/toc_template.md
  pattern-categorization/.gitignore
  pattern-categorization/README.md
  pattern-categorization/innersource-program-mind-map.html
  pattern-categorization/innersource-program-mind-map.png
  pattern-categorization/package-lock.json
  pattern-categorization/package.json
Labels: Type - Meta

#347 Core Team Pattern - Improvements
  assets/img/core-team.png
  assets/img/core-team.svg
  pattern-categorization/innersource-program-mind-map.html
  pattern-categorization/innersource-program-mind-map.md
  pattern-categorization/innersource-program-mind-map.png
  patterns/2-structured/core-team.md
Labels: Type - Content Work

#353 Add Flutter example to Service vs. Library
  patterns/2-structured/service-vs-library.md
Labels: Type - Content Work

#354 Cleanup Service vs Libary pattern
  patterns/2-structured/service-vs-library.md
Labels: Type - Content Work

#350 Update introducing-metrics-in-innersource.md
  patterns/1-initial/introducing-metrics-in-innersource.md
Labels: Type - Content Work

#358 Formatting fixes for the "Introducing Metrics in InnerSource" pattern
  patterns/1-initial/introducing-metrics-in-innersource.md
Labels: Type - Content Work

#361 Adding Isabel Drost-Fromm as author to Initial patterns
  patterns/1-initial/explicit-innersource-principles.md
  patterns/1-initial/explicit-shared-ownership.md
  patterns/1-initial/governance-levels.md
Labels: Type - Maintenance / Cleanup

#360 Renaming the keys for the 'Support and Maintenance' group
  patterns/2-structured/maturity-model.md
Labels: Type - Content Work
