Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2022-11, with the labels that each got.

#477 Update changed link
  .github/workflows/link-checker-prs.yml
  patterns/2-structured/service-vs-library.md
  translation/ja/patterns/service-vs-library.md
Labels: Type - Maintenance / Cleanup

#416 RFC Pattern - Adding Know Instance from DAZN
  patterns/2-structured/transparent-cross-team-decision-making-using-rfcs.md
Labels: Type - Content Work, Known Instances, hacktoberfest

#476 Fix GHA deprecation warning (upgrade lychee-action to 1.5.2)
  .github/workflows/link-checker-prs.yml
  .github/workflows/link-checker.yml
Labels: Type - Maintenance / Cleanup

#480 [docs] Add a chart to explain the levels of the mindmap
  pattern-categorization/README.md
Labels: Type - Meta

#481 Fix mailto syntax
  .github/workflows/link-checker-prs.yml
  .github/workflows/link-checker.yml
  patterns/1-initial/source-code-inventory.md
Labels: Type - Maintenance / Cleanup

#484 Upgrade GHA workflows to latest actions and Node 16
  .github/workflows/generate-mindmap.yml
  .github/workflows/lint-patterns.yml
  .github/workflows/markdownlint.yml
  .lycheeignore
  pattern-categorization/package-lock.json
Labels: Type - Maintenance / Cleanup

#357 Extending Governance Levels
  assets/img/flutter-pyramid.svg
  patterns/1-initial/governance-levels.md
Labels: 2-structured, Type - Content Work

#338 pattern draft: Incubator Pipeline
  patterns/1-initial/incubator-pipeline.md
Labels: 1-initial, Type - Content Work

#492 Adding WellSky as a Known Instance to the Core Team pattern
  patterns/1-initial/incubator-pipeline.md
  patterns/2-structured/core-team.md
Labels: :book: Type - Content Work, :tiger2: patterns-in-the-wild

#489 Tidy-up Incubator Pattern
  README.md
  patterns/1-initial/incubator-pipeline.md
Labels: 1-initial, :book: Type - Content Work
