Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2022-09, with the labels that each got.

#446 Add Airbus as known instance of the InnerSource Portal pattern
  patterns/2-structured/innersource-portal.md
Labels: Type - Content Work, Known Instances

#444 Pattern "Extensions to Manage Contributions at Scale"
  patterns/1-initial/extensions-to-manage-contributions-at-scale.md
Labels: 1-initial, Type - Content Work

#455 Update introducing-metrics-in-innersource.md
  patterns/1-initial/introducing-metrics-in-innersource.md
Labels: Type - Content Work

#456 Add a metric for "Improve quality" in introducing-metrics-in-innersource
  patterns/1-initial/introducing-metrics-in-innersource.md
Labels: Type - Content Work

#457 Add Modern Agile as an anchor to the Concept Anchor pattern
  patterns/1-initial/concept-anchor.md
Labels: 1-initial, Type - Content Work

#459 Use underscore for italics formatting
  patterns/1-initial/concept-anchor.md
Labels: Type - Maintenance / Cleanup

#460 Correcting typo
  patterns/2-structured/document-your-guiding-principles.md
Labels: Type - Content Work

#463 Add new images for Standard Base Documentation
  assets/img/standard-base-documentation/CONTRIBUTING-for-contributors.png
  assets/img/standard-base-documentation/README-for-users.png
  assets/img/standard-base-documentation/README.md
  patterns/2-structured/project-setup/base-documentation.md
Labels: Type - Content Work
