Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2022-10, with the labels that each got.

#377 Create transitioning-contractor-code-to-innersource-model
  patterns/1-initial/transitioning-contractor-code-to-innersource-model.md
Labels: 1-initial, Type - Content Work

#468 Formatting changes to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest

#471 Link Check just for files in a PR
  .github/workflows/link-checker-prs.yml
  .github/workflows/link-checker.yml
  TRUSTED-COMMITTERS.md
Labels: Type - Meta
