Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2023-10, with the labels that each got.

#595 Improved Trusted Committer documentation
  TRUSTED-COMMITTERS.md
Labels: :gear: Type - Meta

#593 Create pattern-metrics.yaml
  .github/workflows/pattern-metrics.yaml
Labels: :gear: Type - Meta

#598 [GHA issue metrics] Make the codeowners uniq
  .github/workflows/pattern-metrics.yaml
Labels: :gear: Type - Meta

#600 Fix URLs of images used by the WelcomeBot
  .github/config.yml
Labels: Type - Maintenance / Cleanup, :gear: Type - Meta

#602 Add monthly contributors report
  .github/workflows/contributor-report.yaml
Labels: Type - Maintenance / Cleanup, :gear: Type - Meta

#606 Translation of new InnerSource Patterns into Brazilian Portuguese
  translation/pt-br/patterns/30-day-warranty.md
  translation/pt-br/patterns/base-documentation.md
  translation/pt-br/patterns/common-requirements.md
  translation/pt-br/patterns/communication-tooling.md
  translation/pt-br/patterns/contracted-contributor.md
  translation/pt-br/patterns/core-team.md
  translation/pt-br/patterns/crossteam-project-valuation.md
  translation/pt-br/patterns/dedicated-community-leader.md
  translation/pt-br/patterns/document-your-guiding-principles.md
  translation/pt-br/patterns/extensions-for-sustainable-growth.md
  translation/pt-br/patterns/gig-marketplace.md
  translation/pt-br/patterns/group-support.md
  translation/pt-br/patterns/innersource-license.md
  translation/pt-br/patterns/innersource-portal.md
  translation/pt-br/patterns/issue-tracker.md
  translation/pt-br/patterns/maturity-model.md
  translation/pt-br/patterns/praise-participants.md
  translation/pt-br/patterns/release-process.md
  translation/pt-br/patterns/repository-activity-score.md
  translation/pt-br/patterns/review-committee.md
  translation/pt-br/patterns/service-vs-library.md
  translation/pt-br/patterns/start-as-experiment.md
  translation/pt-br/patterns/transparent-cross-team-decision-making-using-rfcs.md
  translation/pt-br/patterns/trusted-committer.md
Labels: Type - Translation
