Repository InnerSourceCommons/InnerSourcePatterns, pull requests merged in 2024-12, with the labels that each got.

#737 Actions are changed from default branch to version-specified.
  .github/workflows/vale.yml
Labels: Type - Maintenance / Cleanup

#681 docs(known-instances): Added SAP to RFC pattern
  patterns/2-structured/transparent-cross-team-decision-making-using-rfcs.md
Labels: 2-structured, :book: Type - Content Work, :tiger2: patterns-in-the-wild

#741 Create dependabot.yml
  .github/dependabot.yml
Labels: Type - Maintenance / Cleanup

#746 Mark link as non-reachable in the Unified Source Code Inventory pattern
  .lycheeignore
  patterns/1-initial/source-code-inventory.md
Labels: 1-initial, :book: Type - Content Work

#747 Fixing GHA generate-mindmap
  .github/workflows/generate-mindmap.yml
  pattern-categorization/gl/innersource-program-mind-map.png
  pattern-categorization/innersource-program-mind-map.html
  pattern-categorization/innersource-program-mind-map.png
  pattern-categorization/pt-br/innersource-program-mind-map.png
Labels: Type - Maintenance / Cleanup
